### ISSUE TITLE
How do I build this on macOS 10.14.6?

### ISSUE THREAD

**Issue by frozenpandaman** [tautcony/webvtt2ass#8]
Getting this error:
```
$ npm install webvtt2ass --global

added 28 packages, and audited 28 packages in 1s

found 0 vulnerabilities
$ webvtt2ass myfile.vtt --output myfile.ass
/usr/local/bin/webvtt2ass: line 1: use strict: command not found
: command not foundtt2ass: line 1: 
/usr/local/bin/webvtt2ass: line 2: syntax error near unexpected token `('
'usr/local/bin/webvtt2ass: line 2: `const webvtt2ass = require("..");
```

The only thing that comes up on Google is making sure there's a shebang (`#!/usr/bin/env node`) before the `"use strict";` line in webvtt2ass.js which is already present.

**Comment by tautcony** [comment]
I'll republish latest package to npm registry.

**Comment by frozenpandaman** [comment]
Thanks so much!

It seems that the .js file getting built to `/usr/local/lib/node_modules/webvtt2ass/bin/` (which is then symlinked to `/usr/local/bin/` when doing a global install) has the shebang stripped out from the beginning which causes it to not work. If I manually edit that file to add it in then I can run it successfully:
![image](https://user-images.githubusercontent.com/7245874/114830637-480bb180-9d81-11eb-9915-320a7cc1a5f0.png)

However, it doesn't ever actually produce any output, whether writing to the console or a file:
```
$ webvtt2ass myfile.vtt
$ webvtt2ass myfile.vtt --output 4.ass
```

For reference, my npm is version 7.9.0 and node is v15.3.0.

**Comment by tautcony** [comment]
new version has been published to npm, please run `npm i webvtt2ass -g` again to get latest version.

**Comment by frozenpandaman** [comment]
Works perfectly now! So glad to have this tool, thank you a ton!
