### ISSUE TITLE
Timestamps ending in ".100" instead of rounding up to the next second

### ISSUE THREAD

**Issue by frozenpandaman** [tautcony/webvtt2ass#9]
I've noticed the script generates lines like these, which give milliseconds to three rather than two decimal places:
```
Dialogue: 0,00:09:37.95,00:09:39.100,Default,,0,0,0,blah (line ending time ends with .100)
Dialogue: 0,00:10:22.100,00:10:25.25,Default,,0,0,0,blah (line startime time ends with .100)
```
In the two cases above, the times read `00:09:39.996` and `00:10:22.997` respectively in the original .vtt file.

This bug causes these lines to not display. These should instead be rounded up to the next second, e.g. `00:09:40.00` rather than `00:09:39.100`.

Thanks!

**Comment by tautcony** [comment]
fixed.

**Comment by frozenpandaman** [comment]
Cool, thanks!
